apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-api
  template:
    metadata:
      labels:
        app: notification-api
    spec:
      containers:
        - name: notification-api
          image: sentinelops-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 4000
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:devpassword@host.docker.internal:5432/sentinelops?schema=public"
            - name: REDIS_HOST
              value: "host.docker.internal"
